export const sortOptions = [
    { value: 'published_desc', label: 'Date published (desc)' },
    { value: 'published_asc', label: 'Date published (asc)' },
    { value: 'popularity', label: 'Popularity' },
]

export const categoriesOptions = [
    { value: 'business', label: 'Business', color: '#36B37E' },
    { value: 'entertainment', label: 'Entertainment', color: '#FF8B00' },
    { value: 'general', label: 'General', color: '#0052CC' },
    { value: 'health', label: 'Health', color: '#FF5630' },
    { value: 'science', label: 'Science', color: '#5243AA' },
    { value: 'sports', label: 'Sports', color: '#FFC400' },
    { value: 'technology', label: 'Technology', color: '#666666' },
]

export const countriesOptions = [
    { value: 'ar', label: 'Argentina' },
    { value: 'au', label: 'Australia' },
    { value: 'at', label: 'Austria' },
    { value: 'be', label: 'Belgium' },
    { value: 'br', label: 'Brazil' },
    { value: 'bg', label: 'Bulgaria' },
    { value: 'ca', label: 'Canada' },
    { value: 'cn', label: 'China' },
    { value: 'co', label: 'Colombia' },
    { value: 'cz', label: 'Czech Republic' },
    { value: 'eg', label: 'Egypt' },
    { value: 'fr', label: 'France' },

    { value: 'de', label: 'Germany' },
    { value: 'gr', label: 'Greece' },
    { value: 'hk', label: 'Hong Kong' },
    { value: 'hu', label: 'Hungary' },
    { value: 'in', label: 'India' },
    { value: 'id', label: 'Indonesia' },
    { value: 'ie', label: 'Ireland' },
    { value: 'il', label: 'Israel' },
    { value: 'it', label: 'Italy' },
    { value: 'jp', label: 'Japan' },

    { value: 'lv', label: 'Latvia' },
    { value: 'lt', label: 'Lithuania' },
    { value: 'my', label: 'Malaysia' },
    { value: 'mx', label: 'Mexico' },
    { value: 'ma', label: 'Morocco' },
    { value: 'nl', label: 'Netherlands' },
    { value: 'nz', label: 'New Zealand' },
    { value: 'ng', label: 'Nigeria' },
    { value: 'no', label: 'Norway' },
    { value: 'ph', label: 'Philippines' },

    { value: 'pl', label: 'Poland' },
    { value: 'pt', label: 'Portugal' },
    { value: 'ro', label: 'Romania' },
    { value: 'sa', label: 'Saudi Arabia' },
    { value: 'rs', label: 'Serbia' },
    { value: 'sg', label: 'Singapore' },
    { value: 'sk', label: 'Slovakia' },
    { value: 'si', label: 'Slovenia' },
    { value: 'za', label: 'South Africa' },
    { value: 'kr', label: 'South Korea' },

    { value: 'se', label: 'Sweden' },
    { value: 'ch', label: 'Switzerland' },
    { value: 'tw', label: 'Taiwan' },
    { value: 'th', label: 'Thailand' },
    { value: 'tr', label: 'Turkey' },
    { value: 'ae', label: 'UAE' },
    { value: 'ua', label: 'Ukraine' },
    { value: 'gb', label: 'United Kingdom' },
    { value: 'us', label: 'United States' },
    { value: 've', label: 'Venezuela' },
]

export const languagesOptions = [
    { value: 'ar', label: 'Arabic' },
    { value: 'zh', label: 'Chinese' },
    { value: 'nl', label: 'Dutch' },

    { value: 'en', label: 'English' },
    { value: 'fr', label: 'French' },
    { value: 'de', label: 'German' },
    { value: 'he', label: 'Hebrew' },
    { value: 'it', label: 'Italian' },
    { value: 'no', label: 'Norwegian' },
    { value: 'pt', label: 'Portuguese' },
    { value: 'ru', label: 'Russian' },
    { value: 'es', label: 'Spanish' },
    { value: 'sw', label: 'Swedish' },
]
